// Activity
export const ADD_ACTIVITY_REQUEST = "activity/ADD_ACTIVITY_REQUEST";
export const ADD_ACTIVITY_SUCCESS = "activity/ADD_ACTIVITY_SUCCESS";
export const ADD_ACTIVITY_FAILURE = "activity/ADD_ACTIVITY_FAILURE";

export const GET_ALL_ACTIVITIES_REQUEST = "activity/GET_ALL_ACTIVITIES_REQUEST";
export const GET_ALL_ACTIVITIES_SUCCESS = "activity/GET_ALL_ACTIVITIES_SUCCESS";
export const GET_ALL_ACTIVITIES_FAILURE = "activity/GET_ALL_ACTIVITIES_FAILURE";
